 /*========================================================================================================
  Retrieving Buisness Insights from a multiple table
  ========================================================================================================*/
  --give me all combinations of our employees and vendors. Please show id and names of our employees and vendors
  SELECT EmployeeID,CONCAT(EmployeeFirstName, ' ', EmployeeLastName) AS EmployeeName, VendorID, VendorName
  FROM [SalesOrderStore].[dbo].[Employees] CROSS JOIN [SalesOrderStore].[dbo].[Vendors]
  --Please give me a list of all customers. Please show every customer's id, name and postal address. ie retrieve all matching rows from two tables
  SELECT c.CustomerID, CONCAT(c.CustomerFirstName, ' ', c.CustomerLastName) AS Name, CONCAT(a.StreetAddress, ' ', a.City, ' ', a.StateProvince, ' ', a.Country) AS PostalAddress
  FROM [SalesOrderStore].[dbo].[Customers] AS c
  INNER JOIN [SalesOrderStore].[dbo].[Addresses] AS a ON c.CustomerAddressID = a.AddressID
  --How many customers do we have in each country
  SELECT a.Country, COUNT(CustomerID) AS NumberOfCustomers
  FROM [SalesOrderStore].[dbo].[Customers] AS c
  INNER JOIN [SalesOrderStore].[dbo].[Addresses] AS a ON c.CustomerAddressID = a.AddressId
  GROUP BY a.Country

  --Please give me a list of our Canadian customers. Please show every customes id, name, postal address. Ie join to a subset of address table
  SELECT c.CustomerID, CONCAT(c.CustomerFirstName, ' ', c.CustomerLastName) AS Name, CONCAT(a.StreetAddress, ' ', a.City, ' ', a.StateProvince, ' ', a.Country) AS PostalAddress
  FROM [SalesOrderStore].[dbo].[Customers] AS c
  INNER JOIN 
  (
	SELECT AddressId, StreetAddress, City, StateProvince, Country
	FROM [SalesOrderStore].[dbo].[Addresses] 
	WHERE Country = 'Canada'
  )AS a ON c.CustomerAddressID = a.AddressID
 
  --Please give me a list of our Canadian customers. Please show every customes id, name, postal address. Ie filter in where
  SELECT c.CustomerID, CONCAT(c.CustomerFirstName, ' ', c.CustomerLastName) AS Name, CONCAT(a.StreetAddress, ' ', a.City, ' ', a.StateProvince, ' ', a.Country) AS PostalAddress
  FROM [SalesOrderStore].[dbo].[Customers] AS c
  INNER JOIN [SalesOrderStore].[dbo].[Addresses] AS a ON c.CustomerAddressID = a.AddressID
  WHERE a.Country = 'Canada'
 
 --How many customers do we have in each country
  SELECT a.Country, COUNT(CustomerID) AS NumberOfCustomers
  FROM [SalesOrderStore].[dbo].[Customers] AS c
  INNER JOIN [SalesOrderStore].[dbo].[Addresses] a ON c.CustomerID = a.AddressID
  GROUP BY a.Country
 
 --How many female customers do we have in each country
  SELECT a.Country, COUNT(CustomerID) AS NumberOfCustomers
  FROM [SalesOrderStore].[dbo].[Customers] AS c
  INNER JOIN [SalesOrderStore].[dbo].[Addresses] a ON c.CustomerID = a.AddressID
  WHERE c.CustomerGender = 'Female'
  GROUP BY a.Country
 
 --Would like a list showing out products sold in 2017 generated more than $140,000 revenue.  Please give me the percentage of revenue generated by each product in addition to the product name, number of orders we delivered in 2017, and total revenue generated by each product p.235
  SELECT p.ProductName, COUNT(so.SalesOrderId) AS NumberOfOrders,SUM(so.ProductQuantity * so.ProductUnitPrice - so.ProductQuantity * ProductUnitPriceDiscount) AS TotalProdRevenue
  FROM [SalesOrderStore].[dbo].[SalesOrderProducts] AS so
  INNER JOIN [SalesOrderStore].[dbo].[Products] p ON so.ProductID = p.ProductID
  WHERE YEAR(so.ProductDeliveryDate)=2017
  GROUP BY p.ProductName
  HAVING SUM(so.ProductQuantity * so.ProductUnitPrice - so.ProductQuantity * ProductUnitPriceDiscount) > 140000

  --Would like a list showing out products sold in 2017 generated more than $140,000 revenue.+ Percentage of revenue generated by each product. ie create a temp table called TotalCompanyRevenue so can be used to work out percent
 SELECT ProductSales.ProductName, ProductSales.NumberOfOrders, ProductSales.TotalProductRevenue, (ProductSales.TotalProductRevenue * 100/TotalSales.TotalCompanyRevenue) AS PercentageOfTotal  
 FROM(
 SELECT p.ProductName, COUNT(so.SalesOrderId) AS NumberOfOrders,SUM(so.ProductQuantity * so.ProductUnitPrice - so.ProductQuantity * ProductUnitPriceDiscount) AS TotalProductRevenue
  FROM [SalesOrderStore].[dbo].[SalesOrderProducts] AS so
  INNER JOIN [SalesOrderStore].[dbo].[Products] p ON so.ProductID = p.ProductID
  WHERE YEAR(so.ProductDeliveryDate)=2017
  GROUP BY p.ProductName
  HAVING SUM(so.ProductQuantity * so.ProductUnitPrice - so.ProductQuantity * ProductUnitPriceDiscount) > 140000
)AS ProductSales
CROSS JOIN 
(
	SELECT SUM(ProductQuantity * ProductQuantity - ProductQuantity * ProductUnitPriceDiscount)AS TotalCompanyRevenue
	FROM SalesOrderProducts
)AS TotalSales
ORDER BY TotalProductRevenue DESC

--non matching rows
--We would like to know what feedback (if any) that our customers are giving. Please give me a list of our customers and their feedback (if any)
SELECT c.CustomerLastName, c.CustomerFirstName, cf.ProductID, cf.CustomerFeedbackRating, cf.CustomerFeedback
FROM [SalesOrderStore].[dbo].[Customers] AS c
LEFT OUTER JOIN [SalesOrderStore].[dbo].[CusromerFeedbacks] AS cf ON c.CustomerID = cf.CustomerID
ORDER BY c.CustomerLastName
--please give me any feedback customers gave us and the country and city they are living & replace NULL with --
SELECT c.CustomerLastName, c.CustomerFirstName, ISNULL(CAST(cf.ProductID AS VARCHAR(10)),'--') AS ProductID, ISNULL(CAST(cf.CustomerFeedbackRating AS VARCHAR(10)),'--') AS FeedbackRating, ISNULL(CAST(cf.CustomerFeedback AS VARCHAR(10)),'--') AS FeedbackText, a.city, a.country
FROM [SalesOrderStore].[dbo].[Customers] AS c
LEFT OUTER JOIN [SalesOrderStore].[dbo].[CusromerFeedbacks] AS cf ON c.CustomerID = cf.CustomerID
LEFT OUTER JOIN [SalesOrderStore].[dbo].[Addresses] AS a ON c.CustomerAddressID = a.AddressId
ORDER BY a.country, a.city, c.CustomerLastName
--please give me a list of our United States customers who have not yet provided any feedback
SELECT a.City, c.CustomerFirstName, c.CustomerFirstName
FROM [SalesOrderStore].[dbo].[Customers] AS c
LEFT OUTER JOIN [SalesOrderStore].[dbo].[CusromerFeedbacks] AS cf ON c.CustomerID = cf.CustomerID
LEFT OUTER JOIN [SalesOrderStore].[dbo].[Addresses] AS a ON c.CustomerAddressID = a.AddressId
WHERE a.Country LIKE 'United States' AND cf.CustomerFeedbackRating IS NULL
ORDER BY a.city, c.CustomerFirstName
--Please give me a list of countries where more than 4 customers havent provided any feedback
SELECT a.Country, COUNT(DISTINCT c.CustomerID) AS NumberOfCustomers
FROM Customers AS c
INNER JOIN Addresses AS a ON c.CustomerAddressID = a.AddressId
LEFT OUTER JOIN [SalesOrderStore].[dbo].[CusromerFeedbacks] AS cf ON c.CustomerID = cf.CustomerID
WHERE cf.CustomerFeedbackRating IS NULL
GROUP BY a.Country
HAVING COUNT(DISTINCT c.CustomerID)>4
--need to merge 2 or more disimilar tables
--Please give me a list of vendors, customers and employees
SELECT VendorName AS Name, VendorEmail AS Email, VendorPhoneNumber AS ContactNumber
FROM [SalesOrderStore].[dbo].[Vendors]
UNION
SELECT CONCAT(CustomerFirstName, ' ', CustomerLastName) AS Name, CustomerEmail AS Email, CustomerPhoneNumber AS ContactNumber
FROM [SalesOrderStore].[dbo].[Customers]
UNION
SELECT CONCAT(EmployeeFirstName, ' ',EmployeeLastName) AS Name, EmployeeEmail AS Email, EmployeePhoneNumber AS ContactNumber
FROM [SalesOrderStore].[dbo].[Employees]
--Please give me a list of vendors, customers and employees who are located within USA
SELECT v.VendorName AS Name, v.VendorEmail AS Email, v.VendorPhoneNumber AS ContactNumber
FROM [SalesOrderStore].[dbo].[Vendors] AS v
INNER JOIN [SalesOrderStore].[dbo].[Addresses] AS a ON v.VendorAddressID=a.AddressID
WHERE a.Country LIKE 'United State'
UNION
SELECT CONCAT(c.CustomerFirstName, ' ', c.CustomerLastName) AS Name, c.CustomerEmail AS Email, c.CustomerPhoneNumber AS ContactNumber
FROM [SalesOrderStore].[dbo].[Customers] AS c
INNER JOIN [SalesOrderStore].[dbo].[Addresses] AS a ON c.CustomerAddressID=a.AddressID
WHERE a.Country LIKE 'United State'
UNION
SELECT CONCAT(e.EmployeeFirstName, ' ',e.EmployeeLastName) AS Name, e.EmployeeEmail AS Email, e.EmployeePhoneNumber AS ContactNumber
FROM [SalesOrderStore].[dbo].[Employees] AS e
INNER JOIN [SalesOrderStore].[dbo].[Addresses] AS a ON e.EmployeeAddressID=a.AddressID
WHERE a.Country LIKE 'United State'
--Pleae give me results on a regular basis, but without requesting a specific report
CREATE VIEW ProductView
AS
SELECT * FROM [SalesOrderStore].[dbo].[Products]
--Please give me a list of employees along with their manager's details. ie inner join on the same table
SELECT e1.EmployeeID, CONCAT(e1.EmployeeFirstName,' ',e1.EmployeeLastName) AS EmployeeName, e1.ManagerID, CONCAT(e2.EmployeeFirstName,' ',e2.EmployeeLastName) AS ManagerName
FROM [SalesOrderStore].[dbo].[Employees] e1
INNER JOIN [SalesOrderStore].[dbo].[Employees] e2 ON e1.ManagerID = e2.EmployeeID
--Please give me a list of customers that have bought both product ID 53 & product 55
CREATE VIEW CustomerProducts
AS
SELECT DISTINCT c.CustomerID, CONCAT(c.CustomerFirstName,' ',c.CustomerLastName) AS CustomerName, c.CustomerEmail, sop.ProductID
FROM [SalesOrderStore].[dbo].[Customers] AS c
INNER JOIN [SalesOrderStore].[dbo].[SalesOrders] AS so ON c.CustomerID = so.CustomerID
INNER JOIN [SalesOrderStore].[dbo].[SalesOrderProducts] AS sop ON so.SalesOrderId = sop.SalesOrderId

SELECT Product53.CustomerID, Product53.CustomerName, Product53.CustomerEmail
FROM CustomerProducts AS Product53
INNER JOIN CustomerProducts AS Product55 ON product53.CustomerID = product55.CustomerID
WHERE Product53.ProductID = 53 AND Product55.ProductID = 55
